<?php $orderStatus = $block->getOrderStatus() ?? 'opened'?>
<section class="admin__page-section tcs-shipping-block">
    <div class="admin__page-section-title"><strong class="title"><?=$block->escapeHtml(__('Warehouse')) ?></strong></div>
    <div class="admin__page-section-content">
        <?php echo $this->getBlockHtml('formkey')?>
        <input type="hidden" name="warehouse" id="warehouse" value="<?= $block->getOrderWarehouseByGetOrderId() ?>" />
        <input type="hidden" name="orderid" id="orderid" value="<?= $block->getOrderId() ?>" />
        <div class="admin__field">
            <label for="warehouse" class=""><?= $block->escapeHtml(__('Warehouse for this order:')) ?></label>
            <?php if(in_array($orderStatus, $block->excludedOrderStatus())){?>
                <label for="warehouse" class="admin__field-label"><?= $block->getOrderWarehouseByGetOrderId()?></label>
             <?php } else { ?>
            <div class="admin__field-control">
                <select name="new_warehouse" id="new_warehouse" class="admin__control-select">
                    <option></option>
                    <?php foreach ($block->getWarehouse() as $_code => $_label) : ?>
                        <option value="<?= $block->escapeHtmlAttr($_code) ?>"<?php if ($_code === $block->getOrderWarehouseByGetOrderId()) : ?> selected="selected"<?php endif; ?>><?= $block->escapeHtml($_label) ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <?php } ?>
        </div>
    </div>
</section>
<script>
    require([
        'jquery',
    ],function(){
        jQuery(document).ready(function() {
            jQuery("#new_warehouse").change(function(){

                var warehouse = jQuery("input[name='warehouse']").val();
                var new_warehouse = jQuery("select[name='new_warehouse']").val();
                var orderId = jQuery("input[name='orderid']").val();
                var formKey = jQuery("[name='form_key']").val();

                var url = '/<?= $this->helper('Magento\Backend\Helper\Data')->getAreaFrontName()?>/warehouse/update';
                if(new_warehouse !== warehouse){
                    jQuery.ajax({
                        url: url,
                        type: "POST",
                        data: {orderid:orderId,warehouse:new_warehouse,form_key:formKey},
                        showLoader: true,
                        cache: false,
                        success: function(response){
                            jQuery("select[name='warehouse']").val(new_warehouse);
                            console.log(response.output);
                        }
                    });
                    return false;
                }
            });
        });
    });
</script>